
command_prefix = "$"

desc = "Pwease end my misewy, nyaaa~"

[messages]

file = "./msgs.csv"

[bottom]

executable = "bottomify"

[api_tokens]

#cute cat pictures nyaaa~
#catapi = ""

#discord
#discord = ""
